### ISSUE TITLE
Views do not work well when switching among tree tabs

### ISSUE THREAD

**Issue by ralf-dzq** [webix-hub/webix-adminapp-demo#2]
At first **datatable** view works well like below.
![datatable-ok](https://cloud.githubusercontent.com/assets/7816055/8391543/3ff9e06e-1d0a-11e5-8052-1031602ed509.png)

Now, I want to watch **charts**, so I click chart tree tab. Then it shows me this view:
![charts-wrong](https://cloud.githubusercontent.com/assets/7816055/8391542/3ff6f49e-1d0a-11e5-81b1-ca78b3aa4d38.png)

When I refresh the view(F5), it will come into a right view.
![charts-ok](https://cloud.githubusercontent.com/assets/7816055/8391541/3ff6aaf2-1d0a-11e5-9a6e-8f22060278c0.png)

However, when going back to **datatable** by click its tab, it will show this:
![datatable-wrong](https://cloud.githubusercontent.com/assets/7816055/8391544/3ffa5404-1d0a-11e5-98bd-654d5d1331dd.png)

> **Is that an issue?**

**Comment by Bodom78** [comment]
Noticed this too, resizing or reloading will render the views correctly.

**Comment by mkozhukh** [comment]
The issue fixed in latest version of Webix Jet ( was related to the core library, no to the demo app itself )
