### ISSUE TITLE
Tables are loaded twice when using remote datasource

### ISSUE THREAD

**Issue by kroupa1985** [webix-hub/webix-adminapp-demo#4]
Hi,

I am using remote datasource api, when i am creating datatables. In menu i have different views, with each own datatable component. The admin is composed same as the provided demo app.

The problem occurs, when different view is accessed. The tables are loaded twice. I think that view is loaded twice, because if i open an form in window, after few seconds everything is closed. After loading the second time the app works beautifuly. This thing occurs also when the app is initialy loaded.

Is this a angular isshue or from webix? Please help. I dont know how to correct this problem. 

I can provide a link to app, if anybody wishes.

Regards, Dejan!

**Comment by mkozhukh** [comment]
Most probably the Issue was related to the double repainting of view. Must not be actual for Webix Jet 1.x
