### ISSUE TITLE
"This version of this platfrom is not inteded to use outside of webix.com"

### ISSUE THREAD

**Issue by Doogiemuc** [webix-hub/webix-adminapp-demo#6]
Hi only cloned the repo did a "npm install" and started the demo with "npm start".
Then I get the error/warning message "This version of this platfrom is not inteded to use outside of webix.com" at the top right of the UI.  

Does this demo use the pro version of webix? Or can I use this demo as a base for my open source app?

**Comment by Doogiemuc** [comment]
Replaceing  `//cdn.webix.com/site/webix.js` with `//cdn.webix.com/edge/webix.js`  removes the warning.  But is this ok for my open source licence project?

**Comment by mkozhukh** [comment]
Project was updated to use the "edge" version of Webix UI.

You can use "edge" version in any kind of open source project.
